# Generated by Django 3.1.1 on 2020-09-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='typecategory',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
