# Generated by Django 3.1.1 on 2020-09-06 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200905_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='koran_name',
            new_name='korean_name',
        ),
    ]
