# Generated by Django 3.0.8 on 2020-09-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200904_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltag',
            name='detail',
            field=models.TextField(),
        ),
    ]
