# Generated by Django 3.0.8 on 2020-09-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200906_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
            ],
            options={
                'db_table': 'html_tags',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='english_name',
        ),
        migrations.AddField(
            model_name='product',
            name='korean_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='typecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AddField(
            model_name='htmltag',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
