# Generated by Django 3.0.8 on 2020-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200907_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='korean_name',
            field=models.CharField(max_length=64),
        ),
    ]
