# Generated by Django 3.0.8 on 2020-09-10 21:29

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('birthdate', models.DateField(max_length=16, null=True)),
                ('identifier', models.CharField(max_length=64, null=True, unique=True)),
                ('password', models.CharField(max_length=256, null=True, validators=[user.validators.password_validation_function])),
                ('gender', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=17, null=True, unique=True, validators=[user.validators.phone_number_validation_function])),
                ('kakao_user', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
