# Generated by Django 3.0.8 on 2020-09-01 10:59

from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('birthdate', models.DateField(max_length=16)),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=256, validators=[user.validators.password_validation_function])),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[user.validators.phone_number_validation_function])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Gender')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
