# Generated by Django 3.0.8 on 2020-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200901_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_user',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
