# Generated by Django 3.0.8 on 2020-09-04 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_kakao_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kakao_user',
        ),
    ]
