# Generated by Django 3.0.8 on 2020-09-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_kakao_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
