# Generated by Django 3.0.8 on 2020-09-06 17:34

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200906_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, null=True, unique=True, validators=[user.validators.phone_number_validation_function]),
        ),
    ]
